### ISSUE TITLE
Add support for pluggable compression/decompression for Squashfs?

### ISSUE THREAD

**Issue by xoofx** [LTRData/DiscUtils#13]
Hey, firstly I would like to say that I greatly appreciate the effort to maintain this fork, keep up the good work! ☺️ 

I have been trying to use squashfs but discovered that it only supports Zlib compression/decompression. Not surprising because that's the only supported compression library that is builtin in .NET! 😅 

As there is quite a zoo of compression libs for other formats with various versions - managed and native wrappers, I have made a small prototype in a branch to add support for pluggable compression/decompression. The changes are very minimal, just a few lines of code here and there.

Would you be open for this feature If I create a PR?

**Comment by Olof-Lagerkvist** [comment]
I agree that would be very useful and make it easier to implement support for different compression algorithms. There are lots of third-party .NET libraries that implement various compression algorithms and also .NET wrappers for native libraries.

If you make the change and make a PR, I am happy to include it!

**Comment by xoofx** [comment]
@LTRData have you been able to make progress on merging back my PR to main? What is left?

**Comment by Olof-Lagerkvist** [comment]
Yes sorry, I have been very busy lately. I will most probably merge it and build new nuget packages in the next few days now!
