### ISSUE TITLE
Support only .NET 8+?

### ISSUE THREAD

**Issue by xoofx** [LTRData/DiscUtils#17]
Hey, 

While working on adding proper FAT+LFN support in #15 and experiencing a bit more with the code base, I have found it a bit laborious to have to handle all the old framework/profiles `net46`/`net48`/`netstandard2.0`/`netstandard2.1` (and also, `net7.0` which is not really supported by MSFT, and `net6.0` which EOL is going to happen in 2 months).

So, the question is: @LTRData are you actively using these profiles or is there a plan to get rid of them?

Then, could we only only support .NET8.0+ moving forward? Considering that folks could still download old NuGet packages or even go back to the original forked repo.

Feel free to disregard completely if there is a strong case to have support for these profiles. ☺️

**Comment by Olof-Lagerkvist** [comment]
Regarding .NET 7.0, i plan to drop that in the next package. .NET 6.0 will be dropped when it goes EOL and .NET 9.0 will be added instead.

Regarding .NET Standard 2.0 and 2.1 and .NET Framework 4.6 and 4.8, these are still supported runtimes. They are useful in some cases where it is not possible to use "modern" .NET runtimes. There are still some consumers of these versions out there, so I really do not want to drop them at this point.

I have tried to make it as smooth as possible to still support them by providing large amounts of extension methods implementing `Span` etc overloads to methods and similar, with compatibility implementations for older frameworks. We could add new such ones too where it makes things easier!

**Comment by xoofx** [comment]
> I have tried to make it as smooth as possible to still support them by providing large amounts of extension methods implementing Span etc overloads to methods and similar, with compatibility implementations for older frameworks. We could add new such ones too where it makes things easier!

Yeah, some are more complicated to bring and require entirely different code paths. For example, at some point in my experiment with FAT, I was going to start to use `InlineArray` attribute but I had to implement a different version entirely for older < .NET 8. Several static functions in `MemoryMarshal` are not available in older profiles and are impossible to use. Adding a compatibility layer is less practical because these are static methods (and others are already partly defined in the System.Memory NuGet package)

To work around these problems, I have added unsafe to the FAT project or I had to implement my own stuffs (e.g int.TryFormat with hex that I reimplemented locally with a small helper function to avoid allocations). In the end, that should be fine, these are relatively minor stuffs, but it adds a cognitive load / less pleasant IDE experience (duplicated compilation errors...etc.)

But fair enough, if you have actual users really depending on these profiles, it can happen on some of my OSS projects as well, so I understand such constraints. 😅

**Comment by Olof-Lagerkvist** [comment]
I would think that we could drop support for .NET Framework 4.6 and .NET Standard 2.0 in some near future. It looks like those are not much used. But at least one .NET Framework version is still useful to support because they tend to be actively used. Though, dropping .NET Framework 4.6 and .NET Standard 2.0 does not help much for the cases like in your examples here.
