### ISSUE TITLE
Failed to create ISO file with extremely long file path using CDBuilder

### ISSUE THREAD

**Issue by QianMoXi** [LTRData/DiscUtils#20]
When creating an offline installation package for Visual Studio 2022, some file paths are extremely long:  

```
D:\Layout\Microsoft.VisualStudio.Debugger.Concord.Remote.Resources,version=17.12.35504.99,chip=x64,language=en-US,productarch=neutral,machinearch=ARM64\payload.vsix
```

The ISO file generated by CDBuilder is corrupted and cannot be read. Is there a solution for this?

**Comment by Olof-Lagerkvist** [comment]
Thanks for finding this! It seems it overwrites other directory entry information with parts of the long name. I'll look into it and see what we can do about it!

**Comment by Olof-Lagerkvist** [comment]
It turns out it did not really validate file name length in all code paths. Number of bytes in a file name needs to be at most 256 bytes, which corresponds to 128 characters for UTF-16. So, the maximum file name length is 128. I just checked in a change that makes it throw an exception instead if file name length is too long.

Thanks again for reporting this!

**Comment by QianMoXi** [comment]
I know so little about ISO9960.

But I found out that in UltraISO software, it is possible to set the file name format to support up to 221 characters, how is this possible? The ISO file created in this way can be loaded and used with windows explorer.
![image](https://github.com/user-attachments/assets/ea172768-be92-4a65-850b-26c447c3c20f)

This is the file it created:
[Demo.zip](https://github.com/user-attachments/files/17885924/Demo.zip)

**Comment by Olof-Lagerkvist** [comment]
I am not sure really how they implement that. They probably do not save UTF-16 versions of file names but instead use some other character encoding.

**Comment by QianMoXi** [comment]
Well, I verified again that it just saves the path truncated, there's no way for ISO9960 to support such a long name.

```
expect:
Microsoft.VisualStudio.Debugger.Concord.Remote.Resources,version=17.12.35504.99,chip=x64,language=en-US,productarch=neutral,machinearch=ARM64

actual:
Microsoft.VisualStudio.Debugger.Concord.Remote.Resources,version=17.12.35504.99,chip=x64,language=en-US,produc
```

I need to use the UDF file system to be able to save such a long name. 

But there is only UdfReader in DiscUtils, no way to generate such a file.

It takes a lot of work to realize the UdfBuilder, so I'm going to close this issue.
