### ISSUE TITLE
iso file has one more directory which has a random name like 'a\', 'E\'.

### ISSUE THREAD

**Issue by adfansong** [LTRData/DiscUtils#8]
I use CDReader or VirtualDisk.OpenDisk to GetDirectories("") of an iso file, there's one more directory which has a random name like 'a\', 'E\'.

**Comment by Olof-Lagerkvist** [comment]
ISO images are not normally opened using `VirtualDisk.OpenDisk` but instead using one of the file system recognizers or directly using `CDReader` or `UdfReader` classes. Could you post some example code that shows when the issue happens?

**Comment by adfansong** [comment]
> ISO images are not normally opened using `VirtualDIsk.OpenDisk` but instead using one of the file system recognizers or directly using `CDReader` or `UdfReader` classes. Could you post some example code that shows when the issue happens?

Thanks for your reply. 

I rewrite a simple test.

`var path = FileUtility.pathCombine(FileUtility.persistentPath, "Root/zip/test.iso");
            using (var fs = File.OpenRead(path)) {
                var cd = new CDReader(fs, true);
                var dirs = cd.GetDirectories("");
                print(string.Join('\n', dirs));
                var files = cd.GetFiles("");
                print(string.Join('\n', files));
            }`

Output:
\I
\01-U01.MP3
\02-U02.MP3
\03-U03.MP3
\04-U04.MP3
\05-U05.MP3
\06-U06.MP3
\07-U07.MP3
\08-U08.MP3
\09-U09.MP3
\10-U10.MP3
\11-U11.MP3
\12-U12.MP3
\13-U13.MP3
\14-U14.MP3
\15-U15.MP3

test.iso is like this:
![image](https://github.com/LTRData/DiscUtils/assets/19238023/b3e34659-3d1e-420b-b996-574473ccdc45)

The orignal repo is ok for this.

**Comment by Olof-Lagerkvist** [comment]
Strange. I cannot seem to reproduce anything like that on any ISO images that I have here.

**Comment by adfansong** [comment]
> Strange. I cannot seem to reproduce anything like that on any ISO images that I have here.

Maybe it's a platform issue.

It's ok to run the lib test in VS.

But it's wrong to run the simple test in Unity Mono netstd2.1.

**Comment by Olof-Lagerkvist** [comment]
> > Strange. I cannot seem to reproduce anything like that on any ISO images that I have here.
> 
> Maybe it's a platform issue.
> 
> It's ok to run the lib test in VS.
> 
> But it's wrong to run the simple test in Unity Mono netstd2.1.

Not sure really. Any chance you could share an iso image where you see this behavior?

**Comment by adfansong** [comment]
> > > Strange. I cannot seem to reproduce anything like that on any ISO images that I have here.
> > 
> > 
> > Maybe it's a platform issue.
> > It's ok to run the lib test in VS.
> > But it's wrong to run the simple test in Unity Mono netstd2.1.
> 
> Not sure really. Any chance you could share an iso image where you see this behavior?

OK, I uploaded one iso file here:

[https://wwf.lanzouo.com/ie5dc1uzhs5c](https://wwf.lanzouo.com/ie5dc1uzhs5c)

Input the password:
f8tg

If you still can't reproduce it and you have enough time, you can try to install a Unity v2022.

Thanks for your support.

**Comment by Olof-Lagerkvist** [comment]
Thanks for the test file! I can see that there is something strange in the .NET Standard 2.1 version. I also realize that the .NET Standard versions of the libraries are not really tested in the build process, something that should be implemented to catch anomalies like this.

I'll try to figure out what is happening and how it could be fixed!

**Comment by Olof-Lagerkvist** [comment]
I saw some issues with how it concatenates paths in .NET Standard versions of the library when running on non-Windows systems. Just made a commit with a change that fixes this:
https://github.com/LTRData/DiscUtils/commit/897da6f67744355c5bbc0084936490ebd9f32a08

I have not tested in Unity yet, so I am not entirely sure whether it is actually the same error as you found.

**Comment by adfansong** [comment]
> I saw some issues with how it concatenates paths in .NET Standard versions of the library when running on non-Windows systems. Just made a commit with a change that fixes this: [897da6f](https://github.com/LTRData/DiscUtils/commit/897da6f67744355c5bbc0084936490ebd9f32a08)
> 
> I have not tested in Unity yet, so I am not entirely sure whether it is actually the same error as you found.

Thanks for your fix.

I've updated the code, but the issue still exists.

![image](https://github.com/LTRData/DiscUtils/assets/19238023/35fcc054-89bd-4d68-a0d7-ba705fc19003)

**Comment by Olof-Lagerkvist** [comment]
Which OS are you running this on?

**Comment by adfansong** [comment]
> Which OS are you running this on?

Windows 10.

Unity platform ios.

**Comment by Olof-Lagerkvist** [comment]
Okay. Unfortunately, I cannot reproduce it on Windows with .NET Standard 2.1 version even with your image file.

**Comment by adfansong** [comment]
> Okay. Unfortunately, I cannot reproduce it on Windows with .NET Standard 2.1 version even with your image file.

OK, thanks for your time.
Maybe it’s the problem of Unity mono.

**Comment by modz2014** [comment]
please send a screenshot @adfansong  of inside the iso

**Comment by DevX-Cipher** [comment]
@adfansong its your code you provided above has little error in it

**Comment by Olof-Lagerkvist** [comment]
> @adfansong its your code you provided above has little error in it 

What is the error?
